### ISSUE TITLE
Support stylelint?

### ISSUE THREAD

**Issue by MLoughry** [microsoft/griffel#422]
I see that the `@griffel/babel-preset` depends on `@linaria`, which in turn [has mechanisms](https://github.com/callstack/linaria/blob/master/docs/LINTING.md) to run [`stylelint`](https://stylelint.io/) over the resulting CSS. However, I cannot seem to get it working with Griffel.

Is there already an undocumented way of doing this that could be documented? Or would it be possible to create a supported way to do this? We already have a number of `stylelint` rules that we would like to re-use after a migration without having to rewrite them as questionable ESLint rules.

**Comment by layershifter** [comment]
> I see that the `@griffel/babel-preset` depends on `@linaria`, which in turn [has mechanisms](https://github.com/callstack/linaria/blob/master/docs/LINTING.md) to run [`stylelint`](https://stylelint.io/) over the resulting CSS. However, I cannot seem to get it working with Griffel.

Currently we use just a part of Linaria that performs module evaluation, in background we are trying to move to v4 (#414), but there are still blockers that prevent us from its adoption 😿 

Fair note: we actively collaborate with Linaria maintainer to resolve them.

> Is there already an undocumented way of doing this that could be documented? Or would it be possible to create a supported way to do this?

There is no way to do this currently, however @ling1726 works on enhanced ESLint rule/plugin that runs against compiled CSS. The benefit of this approach that we can emit errors on source code and don't require build for a feedback loop that makes DX significantly better 💪 

I think that it would be great to embed `stylelint` to these changes. We don't have it in opensource yet, but I will connect you in offline.

**Comment by ling1726** [comment]
Needs some investigation to see if we can implement a stylelint preprocessor for Griffel and get good source mapping support. It's essentially all that Linaria's stylelint package does https://github.com/callstack/linaria/blob/master/packages/stylelint/src/preprocessor.ts

**Comment by NotWoods** [comment]
This is somewhat high priority for Loop. We really need linting for our CSS because our developers are using various too-new CSS features and not testing in older browsers nor testing for all themes we support.

**Comment by RehanSaeed** [comment]
Are there any updates on this? I'd like to use stylelint with Griffel.

**Comment by layershifter** [comment]
@RehanSaeed it's supported already (https://github.com/microsoft/griffel/tree/main/packages/postcss-syntax), but not documented well.

I don't have a complete setup, but the following should work with small tweaks:

```ts
const griffelCustomSyntax = require("@griffel/postcss-syntax");

/** @type {import('stylelint').Config} */
module.exports = {
  rules: rules,
  files: ["*.styles.ts"],
  overrides: [
    {
      files: ["*.styles.ts"],
      customSyntax: griffelCustomSyntax(),
    },
  ],
};
```

**Comment by zbp18** [comment]
Thanks @layershifter, I tried this however adding the griffelCustomSyntax and running stylelint gave us the following errors: "Failed to parse Griffel style" + babel related issues - I tried adding the @babel dependencies suggested to out package.json but I'm still seeing the same errors and something related to a babel config, could this be something we need to add?

`Failed to parse Griffel styles
SyntaxError: /workspaces/1JS/midgard/packages/people-in-taskbar/src/Components/ResultsPage/SearchBox/SearchBox.styles.ts: Unexpected token, expected "from" (1:12)


> 1 | import type { InferStyles } from "@1js/component-styling";
    |             ^
  2 | import { createFluentComponentStyles } from "@1js/component-styling-fluent";
  3 | import { makeStyles, shorthands, tokens } from "@fluentui/react-components";
  4 | import { SEARCHBOX_BUFFER } from "../../../CommonResources/Constants";
    at constructor (/workspaces/1JS/midgard/.store/@babel-parser@7.27.0-bb3e624dd2b9edfe8eca/node_modules/@babel/parser/lib/index.js:360:19)
    at Parser.raise (/workspaces/1JS/midgard/.store/@babel-parser@7.27.0-bb3e624dd2b9edfe8eca/node_modules/@babel/parser/lib/index.js:3338:19)
    at Parser.unexpected (/workspaces/1JS/midgard/.store/@babel-parser@7.27.0-bb3e624dd2b9edfe8eca/node_modules/@babel/parser/lib/index.js:3358:16)
    at Parser.expectContextual (/workspaces/1JS/midgard/.store/@babel-parser@7.27.0-bb3e624dd2b9edfe8eca/node_modules/@babel/parser/lib/index.js:3647:12)
    at Parser.parseImportSpecifiersAndAfter (/workspaces/1JS/midgard/.store/@babel-parser@7.27.0-bb3e624dd2b9edfe8eca/node_modules/@babel/parser/lib/index.js:13903:10)
    at Parser.parseImport (/workspaces/1JS/midgard/.store/@babel-parser@7.27.0-bb3e624dd2b9edfe8eca/node_modules/@babel/parser/lib/index.js:13895:17)
    at Parser.parseStatementContent (/workspaces/1JS/midgard/.store/@babel-parser@7.27.0-bb3e624dd2b9edfe8eca/node_modules/@babel/parser/lib/index.js:12540:27)
    at Parser.parseStatementLike (/workspaces/1JS/midgard/.store/@babel-parser@7.27.0-bb3e624dd2b9edfe8eca/node_modules/@babel/parser/lib/index.js:12432:17)
    at Parser.parseModuleItem (/workspaces/1JS/midgard/.store/@babel-parser@7.27.0-bb3e624dd2b9edfe8eca/node_modules/@babel/parser/lib/index.js:12409:17)
    at Parser.parseBlockOrModuleBlockBody (/workspaces/1JS/midgard/.store/@babel-parser@7.27.0-bb3e624dd2b9edfe8eca/node_modules/@babel/parser/lib/index.js:12980:36)
    at Parser.parseBlockBody (/workspaces/1JS/midgard/.store/@babel-parser@7.27.0-bb3e624dd2b9edfe8eca/node_modules/@babel/parser/lib/index.js:12973:10)
    at Parser.parseProgram (/workspaces/1JS/midgard/.store/@babel-parser@7.27.0-bb3e624dd2b9edfe8eca/node_modules/@babel/parser/lib/index.js:12306:10)
    at Parser.parseTopLevel (/workspaces/1JS/midgard/.store/@babel-parser@7.27.0-bb3e624dd2b9edfe8eca/node_modules/@babel/parser/lib/index.js:12296:25)
    at Parser.parse (/workspaces/1JS/midgard/.store/@babel-parser@7.27.0-bb3e624dd2b9edfe8eca/node_modules/@babel/parser/lib/index.js:14152:10)
    at parse (/workspaces/1JS/midgard/.store/@babel-parser@7.27.0-bb3e624dd2b9edfe8eca/node_modules/@babel/parser/lib/index.js:14186:38)
    at parser (/workspaces/1JS/midgard/.store/@babel-core@7.25.2-2f64570175718935b829/node_modules/@babel/core/lib/parser/index.js:41:34)
    at parser.next (<anonymous>)
    at normalizeFile (/workspaces/1JS/midgard/.store/@babel-core@7.25.2-2f64570175718935b829/node_modules/@babel/core/lib/transformation/normalize-file.js:64:37)
    at normalizeFile.next (<anonymous>)
    at run (/workspaces/1JS/midgard/.store/@babel-core@7.25.2-2f64570175718935b829/node_modules/@babel/core/lib/transformation/index.js:21:50)
    at run.next (<anonymous>)
    at transform (/workspaces/1JS/midgard/.store/@babel-core@7.25.2-2f64570175718935b829/node_modules/@babel/core/lib/transform.js:22:33)
    at transform.next (<anonymous>)
    at evaluateSync (/workspaces/1JS/midgard/.store/gensync@1.0.0-beta.2-6583234ddd3dd39510f3/node_modules/gensync/index.js:251:28)
    at sync (/workspaces/1JS/midgard/.store/gensync@1.0.0-beta.2-6583234ddd3dd39510f3/node_modules/gensync/index.js:89:14)
    at stopHiding - secret - don't use this - v1 (/workspaces/1JS/midgard/.store/@babel-core@7.25.2-2f64570175718935b829/node_modules/@babel/core/lib/errors/rewrite-stack-trace.js:47:12)
    at Object.transformSync (/workspaces/1JS/midgard/.store/@babel-core@7.25.2-2f64570175718935b829/node_modules/@babel/core/lib/transform.js:42:76)
    at transformSync (/workspaces/1JS/midgard/.store/@griffel-postcss-syntax@1.3.1-b78dff1c85f117d88c61/node_modules/@griffel/postcss-syntax/src/transform-sync.js:13:35)
    at parseGriffelStyles (/workspaces/1JS/midgard/.store/@griffel-postcss-syntax@1.3.1-b78dff1c85f117d88c61/node_modules/@griffel/postcss-syntax/src/parse.js:71:59)
    at parse (/workspaces/1JS/midgard/.store/@griffel-postcss-syntax@1.3.1-b78dff1c85f117d88c61/node_modules/@griffel/postcss-syntax/src/parse.js:18:25)
    at new LazyResult (/workspaces/1JS/midgard/.store/postcss@8.5.3-a64fa8e947d997b60d52/node_modules/postcss/lib/lazy-result.js:165:16)
    at Processor.process (/workspaces/1JS/midgard/.store/postcss@8.5.3-a64fa8e947d997b60d52/node_modules/postcss/lib/processor.js:53:14)
    at getPostcssResult (file:///workspaces/1JS/midgard/.store/stylelint@16.18.0-a135e72c71845331ba8f/node_modules/stylelint/lib/getPostcssResult.mjs:50:47)
    at async lintSource (file:///workspaces/1JS/midgard/.store/stylelint@16.18.0-a135e72c71845331ba8f/node_modules/stylelint/lib/lintSource.mjs:85:4)
    at async file:///workspaces/1JS/midgard/.store/stylelint@16.18.0-a135e72c71845331ba8f/node_modules/stylelint/lib/standalone.mjs:241:27
    at async Promise.all (index 34) {
  code: 'BABEL_PARSE_ERROR',
  reasonCode: 'UnexpectedToken',
  loc: Position { line: 1, column: 12, index: 12 },
  pos: 12,
  syntaxPlugin: undefined
}`

**Comment by layershifter** [comment]
Closing this as resolved — stylelint is supported via [`@griffel/postcss-syntax`](https://github.com/microsoft/griffel/tree/main/packages/postcss-syntax), and the two things that were still blocking real use have now been addressed.

**Documentation** (#1049). This was the ask in the later comments. The README is rewritten around the actual use case, and there is now a [Linting with stylelint](https://github.com/microsoft/griffel/blob/main/apps/website/docs/react/guides/linting-with-stylelint.md) guide on the website. @MLoughry, to your original question — existing stylelint rules run unchanged against the generated CSS, so a migration does not require rewriting them as ESLint rules. @ling1726, source mapping works: the PostCSS AST carries locations back to the original file, so problems are reported at the slot in your `.styles.ts`, not in generated CSS.

**@zbp18's parse failure is fixed** (#810). Your `SyntaxError: Unexpected token, expected "from" (1:12)` was our bug, not a missing dependency on your side. The old implementation called Babel with `babelrc: false, configFile: false`, so your `@babel/preset-typescript` was deliberately ignored and `.ts` files were parsed as plain JavaScript. Babel read `type` in `import type { InferStyles }` as a default import binding, then expected `from` and found `{` — hence column 12. Adding `@babel` dependencies could never have helped; the only workaround was threading presets through `babelOptions`.

#810 removed Babel from the package entirely in favour of `@griffel/transform`, which uses [oxc](https://oxc.rs/) and parses TypeScript natively. There is no Babel config involved any more. Your exact input now works:

```ts
import type { InferStyles } from '@1js/component-styling';
import { makeStyles, tokens } from '@fluentui/react-components';

export const useStyles = makeStyles({
  root: { color: tokens.colorNeutralForeground1, paddingLeft: '4px' },
});
```

```
.f19n0e5{color:var(--colorNeutralForeground1);}.fycuoez{padding-left:4px;}.f8wuabp{padding-right:4px;}
```

**Correcting the config posted above.** @layershifter's snippet does not match the package API — the default export is `{ parse, stringify }`, so calling `griffelCustomSyntax()` throws. Sorry for the detour, @zbp18. The supported forms are:

```json
// .stylelintrc.json
{
  "customSyntax": "@griffel/postcss-syntax",
  "rules": { "selector-anb-no-unmatchable": true }
}
```

...or, if you re-export `makeStyles` from your own package:

```js
// stylelint.config.mjs
import { createSyntax } from '@griffel/postcss-syntax';

export default {
  customSyntax: createSyntax({
    importsToTransform: ['@fluentui/react-components', '@1js/component-styling-fluent'],
  }),
};
```

Note that `importsToTransform` *replaces* the default list (`@griffel/core`, `@griffel/react`, `@fluentui/react-components`) rather than extending it.

⚠️ **Not published yet.** #810 is on `main`, but npm still has `@griffel/postcss-syntax@1.3.14`, which is the Babel-based version. The fix ships with the upcoming `2.0.0`, which is also a breaking release: the package becomes ESM only, so a CommonJS project will need `stylelint.config.mjs` instead of `.stylelintrc.js`. If you hit anything after upgrading, please open a new issue.

---

*Disclosure: this reply was generated by an AI agent and reviewed by a maintainer before posting. The root cause above was confirmed against the removed `transform-sync.ts`, and the output shown was produced by running the current implementation on @zbp18's reported input.*
